---
name: Lint

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    uses: DevSecNinja/.github/.github/workflows/lint.yml@c61e8107b080f72e25bfc41d3eef947dbfa66446 # v3.0.0
    permissions:
      contents: read
      security-events: write
    with:
      # renovate: datasource=github-releases depName=jdx/mise
      mise-version: "2026.9.1"
